/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Download } from "./Download";
import { DownloadCountArgs } from "./DownloadCountArgs";
import { DownloadFindManyArgs } from "./DownloadFindManyArgs";
import { DownloadFindUniqueArgs } from "./DownloadFindUniqueArgs";
import { DeleteDownloadArgs } from "./DeleteDownloadArgs";
import { DownloadService } from "../download.service";
@graphql.Resolver(() => Download)
export class DownloadResolverBase {
  constructor(protected readonly service: DownloadService) {}

  async _downloadsMeta(
    @graphql.Args() args: DownloadCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Download])
  async downloads(
    @graphql.Args() args: DownloadFindManyArgs
  ): Promise<Download[]> {
    return this.service.downloads(args);
  }

  @graphql.Query(() => Download, { nullable: true })
  async download(
    @graphql.Args() args: DownloadFindUniqueArgs
  ): Promise<Download | null> {
    const result = await this.service.download(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Download)
  async deleteDownload(
    @graphql.Args() args: DeleteDownloadArgs
  ): Promise<Download | null> {
    try {
      return await this.service.deleteDownload(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
